name = "CuBatchedRoutines"
uuid = "17262254-893e-11e9-36fa-5db3c979532c"
authors = ["Roger-luo"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
